name: {{ cookiecutter.conda_python_env}}

channels:
    - defaults
    - conda-forge
    - astropy

dependencies:
    - python>={{cookiecutter.minimum_python_version}}
    - anaconda
    - astropy
    - h5py
    - numpy
    - pandas
    - matplotlib
    - scipy
    - seaborn
    - sphinx >= 1.6
    - pip
    - pip:
        - GitPython
        - cosmo-utils
        - configparser
{% if cookiecutter.use_astropy_theme_or_RTD == "RTD" %}
    - sphinx_rtd_theme
    - numpydoc
{% endif %}
{% if cookiecutter.use_astropy_theme_or_RTD == "Astropy" %}
    - sphinx-astropy
{% endif %}
        
