name: {{ cookiecutter.conda_python_env}}

channels:
    - defaults
    - conda-forge
    - astropy

dependencies:
    - python>={{cookiecutter.minimum_python_version}}
    - astropy
    - seaborn
    - sphinx >= 1.6
    - pip
    - pip:
        - GitPython
        - configparser
        - sphinx-astropy
        - sphinx-automodapi
        - sphinx_rtd_theme
        
