name: {{ cookiecutter.conda_python_env}}

channels:
  - defaults

dependencies:
    - python>={{cookiecutter.minimum_python_version}}
    - ipython
    - anaconda
    - astropy
    - h5py
    - numpy
    - pandas
    - scipy
    - seaborn
    - sphinx >= 1.6
    - pip >= 18.0
    - pip:
        - GitPython
        - progressbar2
        - cosmo-utils
        - configparser
        - sphinx-astropy
        - sphinx_rtd_theme
