name: {{ cookiecutter.conda_python_env}}

channels:
  - defaults

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - astropy
  - h5py
  - numpy
  - pandas
  - scipy
  - seaborn
  - sphinx
  - pip
  - pip:
    - GitPython
    - progressbar2
    - sphinx_rtd_theme
